language: node_js

node_js:
  - "node"

script:
  - yarn lint
  - yarn test

cache: yarn

addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
